version: '3.8'

services:
  ts3-discord-status:
    build: .
    container_name: ts3-discord-status
    image: rale2k/discord-ts3-status:latest
    restart: unless-stopped
    environment:
      # Required
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CHANNEL_IDS=${DISCORD_CHANNEL_IDS}
      - TS3_HOST=${TS3_HOST}
      - TS3_PASSWORD=${TS3_PASSWORD}
      
      # Optional - currently initialized to defaults
      # - TS3_QUERY_PORT=10011
      # - TS3_SERVER_PORT=TS3_SERVER_PORT
      # - TS3_USERNAME=serveradmin
      # - TS3_NICKNAME=Discord-Bot
      # - TS3_VIRTUAL_SERVER_ID=TS3_VIRTUAL_SERVER_ID
      # - UPDATE_INTERVAL=30
      # - MAX_ACTIVE_SECONDS=30
      # - MAX_AWAY_SECONDS=300
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"