version: '3.8'

services:
  ts3-discord-bot:
    build: .
    container_name: ts3-discord-bot
    restart: unless-stopped
    environment:
      # Required
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - TS3_HOST=${TS3_HOST}
      - TS3_PASSWORD=${TS3_PASSWORD}
      
      # Optional
      - TS3_QUERY_PORT=${TS3_QUERY_PORT:-10011}
      - TS3_SERVER_PORT=${TS3_SERVER_PORT:-9987}
      - TS3_USERNAME=${TS3_USERNAME:-serveradmin}
      - TS3_NICKNAME=${TS3_NICKNAME:-Discord-Bot}
      - TS3_VIRTUAL_SERVER_ID=${TS3_VIRTUAL_SERVER_ID:-1}
      - UPDATE_INTERVAL=${UPDATE_INTERVAL:-30}
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"